name: animated_tree_view
description: Animated TreeView based on AnimatedList that allows building fully customizable Nodes that can be nested to infinite levels and children.
version: 0.1.2
repository: https://github.com/embraceitmobile/animated_tree_view

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  scroll_to_index: ^3.0.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

