name: animated_tree_view
description: Animated TreeView based on AnimatedList that allows building fully customizable Nodes that can be nested to infinite levels and children.
version: 1.1.1+1
repository: https://github.com/embraceitmobile/animated_tree_view

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  scroll_to_index: ^3.0.1
  diffutil_dart: ^3.0.0
  tuple: ^2.0.0
  collection: ^1.17.0

  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.3.2
  test_cov_console: ^0.2.2
  flutter_test:
    sdk: flutter

screenshots:
  - description: 'Simple TreeView usage'
    path: example/screenshots/sample_treeview.png

