name: animated_tree_view
description: A flutter package based on AnimatedList for creating animated tree-views. Fully customizable tree-views can be created using the provided builder. An infinite number of children with infinite levels can be added to the hierarchy.
version: 0.1.1
repository: https://github.com/embraceitmobile/animated_tree_view

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  scroll_to_index: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

