name: animated_tree_view
description: A flutter pacakge for creating animated tree-views
version: 0.5.0
author: jawwad-hassan89
repository: https://github.com/embraceitmobile/animated_tree_view

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  scroll_to_index: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

